import { assets } from "@/lib/assets";

export type CatalogueBrowseSong = {
  title: string;
  artist: string;
  genre: string;
  language: string;
  mood: string;
  coverImage: string;
  audioFileName?: string;
  audioBasePath?: "/catalogue/audio" | "/catalogue/audio-huey-d";
};

export const catalogueBrowseCoverImage = assets.catalogue.mWisSharedCover;

export const catalogueBrowseSongs: CatalogueBrowseSong[] = [
  {
    title: "Always be your child",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Worship / Emotional",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Always be your child.mp3",
  },
  {
    title: "Good Woman",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Romantic / Soul",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Good Woman.mp3",
  },
  {
    title: "Its Time to Move On",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Emotional / Healing",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Its Time to Move On.mp3",
  },
  {
    title: "My Love will last for a Lifetime",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Romantic Ballad",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "My Love will last for a Lifetime.mp3",
  },
  {
    title: "My Wife My Life",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Romantic / Soul",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "My Wife My Life.mp3",
  },
  {
    title: "Ngingasula Okwanamuhla",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "Other",
    mood: "African Spiritual",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ngingasula Okwanamuhla.mp3",
  },
  {
    title: "Ocean Between Us",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Emotional / Distance",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ocean Between Us.mp3",
  },
  {
    title: "Saltwater Eyes",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Coastal / Emotional",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Saltwater Eyes.mp3",
  },
  {
    title: "You're Still Here",
    artist: "M-Wis",
    genre: "Adult Contemporary",
    language: "English",
    mood: "Emotional / Spiritual",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "You’re Still Here.mp3",
  },
  {
    title: "As ek vannag kon uitvee",
    artist: "M-Wis",
    genre: "Afrikaanse Adult Contemporary",
    language: "Afrikaans",
    mood: "Emotional / Reflective",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "As ek vannag kon uitvee.mp3",
  },
  {
    title: "Hier Is Ons",
    artist: "M-Wis",
    genre: "Afrikaanse Adult Contemporary",
    language: "Afrikaans",
    mood: "Uplifting / Unity",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Hier Is Ons.mp3",
  },
  {
    title: "My liefde hou vir ’n leeftyd",
    artist: "M-Wis",
    genre: "Afrikaanse Adult Contemporary",
    language: "Afrikaans",
    mood: "Romantic",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "My liefde hou vir ’n leeftyd.mp3",
  },
  {
    title: "Ons Twee Verdwaal",
    artist: "M-Wis",
    genre: "Afrikaanse Adult Contemporary",
    language: "English",
    mood: "Romantic / Emotional",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ons Twee Verdwaal.mp3",
  },
  {
    title: "Voel Weer",
    artist: "M-Wis",
    genre: "Afrikaanse Adult Contemporary",
    language: "Afrikaans",
    mood: "Reflective / Healing",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Voel Weer.mp3",
  },
  {
    title: "Brood van Lewe",
    artist: "M-Wis",
    genre: "Afrikaans Gospel Ballad",
    language: "Afrikaans",
    mood: "Worship / Spiritual",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Brood van Lewe.mp3",
  },
  {
    title: "Lei Ons Terug Na U, Jesus",
    artist: "M-Wis",
    genre: "Afrikaans Gospel Ballad",
    language: "Afrikaans",
    mood: "Worship",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Lei Ons Terug Na U, Jesus.mp3",
  },
  {
    title: "Ons is nooit Alleen nie",
    artist: "M-Wis",
    genre: "Afrikaans Gospel Ballad",
    language: "Afrikaans",
    mood: "Faith / Comfort",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ons is nooit Alleen nie.mp3",
  },
  {
    title: "Living Bread",
    artist: "M-Wis",
    genre: "Christian Contemporary / CCM",
    language: "English",
    mood: "Spiritual / Reflective",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Living Bread.mp3",
  },
  {
    title: "Daar Kom die Alibama",
    artist: "M-Wis",
    genre: "Cape Folk",
    language: "Afrikaans",
    mood: "Folk / Character",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Daar Kom die Alibama.mp3",
  },
  {
    title: "Dina van District 6",
    artist: "M-Wis",
    genre: "Cape Folk",
    language: "Afrikaans",
    mood: "Storytelling / Cape",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Dina van District 6.mp3",
  },
  {
    title: "Draai Soe",
    artist: "M-Wis",
    genre: "Cape Folk",
    language: "Afrikaans",
    mood: "Dance / Local Pop",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Draai Soe.mp3",
  },
  {
    title: "Kalahari High",
    artist: "M-Wis",
    genre: "Inspirational",
    language: "Afrikaans / English",
    mood: "Desert / Cinematic",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Kalahari High.mp3",
  },
  {
    title: "Re Teng Ga Nyele",
    artist: "M-Wis",
    genre: "Inspirational",
    language: "Other",
    mood: "African Uplifting",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Re Teng Ga Nyele.mp3",
  },
  {
    title: "Afrika Borwa",
    artist: "M-Wis",
    genre: "House",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Afrika Borwa.mp3",
  },
  {
    title: "The Y - Kimberley",
    artist: "M-Wis",
    genre: "House",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "The Y - Kimberley.mp3",
  },
  {
    title: "Tomorrow Land",
    artist: "M-Wis",
    genre: "Dance / EDM",
    language: "English",
    mood: "Festival / Uplifting",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Tomorrow Land.mp3",
  },
  {
    title: "Kurara Easy",
    artist: "M-Wis",
    genre: "Afrobeats",
    language: "Other",
    mood: "Afro / Relaxed",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Kurara Easy.mp3",
  },
  {
    title: "Re Bina Bosigo",
    artist: "M-Wis",
    genre: "Afrobeats",
    language: "Other",
    mood: "Additional catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Re Bina Bosigo.mp3",
  },
  {
    title: "Mirror Noise",
    artist: "M-Wis",
    genre: "Pop",
    language: "English",
    mood: "Alternative / Atmospheric",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Mirror Noise.mp3",
  },
  {
    title: "Strobe Waistline",
    artist: "M-Wis",
    genre: "Trap",
    language: "English",
    mood: "Club / Dance",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Strobe Waistline.mp3",
  },
  {
    title: "Baila Conmigo - Dance with me",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Baila Conmigo - Dance with me.mp3",
  },
  {
    title: "Father & Son Hip Hop Love",
    artist: "M-Wis",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Father & Son Hip Hop Love.mp3",
  },
  {
    title: "Fusion Magic",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Fusion Magic.mp3",
  },
  {
    title: "Growing Up at the Crossroads",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: assets.artists.hueyDProfile,
    audioFileName: "Growing Up at the Crossroads.mp3",
    audioBasePath: "/catalogue/audio-huey-d",
  },
  {
    title: "Huey-D French Inspired",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: assets.artists.hueyDProfile,
    audioFileName: "Heuy-D French Inspired.mp3",
    audioBasePath: "/catalogue/audio-huey-d",
  },
  {
    title: "Miles to Go",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Miles to Go.mp3",
  },
  {
    title: "South side Rhythm",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: assets.artists.hueyDProfile,
    audioFileName: "South side Rythm.mp3",
    audioBasePath: "/catalogue/audio-huey-d",
  },
  {
    title: "Windsor Knot",
    artist: "Huey D",
    genre: "Hip-Hop",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: assets.artists.hueyDProfile,
    audioFileName: "Windsor Knot.mp3",
    audioBasePath: "/catalogue/audio-huey-d",
  },
  {
    title: "Between The Beat & You",
    artist: "M-Wis",
    genre: "Amapiano",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Between The Beat & You.mp3",
  },
  {
    title: "Bom Bom Bom",
    artist: "M-Wis",
    genre: "Amapiano",
    language: "English",
    mood: "Catalogue information available on request",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Bom Bom Bom.mp3",
  },
  {
    title: "Peacock Blue Die Griquas",
    artist: "M-Wis",
    genre: "Anthem",
    language: "Afrikaans / English",
    mood: "Heritage / Cultural",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Peacock Blue Die Griquas.mp3",
  },
];

export const catalogueBrowseArtists = Array.from(
  new Set(catalogueBrowseSongs.map((song) => song.artist)),
).sort();

export const catalogueBrowseGenres = Array.from(
  new Set(catalogueBrowseSongs.map((song) => song.genre)),
).sort();

export const catalogueBrowseLanguages = Array.from(
  new Set(catalogueBrowseSongs.map((song) => song.language)),
).sort();
