import { assets } from "@/lib/assets";

export type CatalogueBrowseSong = {
  title: string;
  artist: "M-WIS";
  genre: string;
  language: string;
  mood: string;
  coverImage: string;
  audioFileName?: string;
};

export const catalogueBrowseCoverImage = assets.catalogue.mWisSharedCover;

export const catalogueBrowseSongs: CatalogueBrowseSong[] = [
  {
    title: "Afrika Borwa",
    artist: "M-WIS",
    genre: "Anthem",
    language: "Afrikaans",
    mood: "African Pride / Cinematic",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Afrika Borwa.mp3",
  },
  {
    title: "As ek vannag kon uitvee",
    artist: "M-WIS",
    genre: "Afrikaans",
    language: "Afrikaans",
    mood: "Emotional / Reflective",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "As ek vannag kon uitvee.mp3",
  },
  {
    title: "Brood van Lewe",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "Afrikaans",
    mood: "Worship / Spiritual",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Brood van Lewe.mp3",
  },
  {
    title: "Dina van District 6",
    artist: "M-WIS",
    genre: "Contemporary",
    language: "Afrikaans",
    mood: "Storytelling / Cape",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Dina van District 6.mp3",
  },
  {
    title: "Good Woman",
    artist: "M-WIS",
    genre: "R&B",
    language: "English",
    mood: "Romantic / Soul",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Good Woman.mp3",
  },
  {
    title: "Its Time to Move On",
    artist: "M-WIS",
    genre: "Contemporary",
    language: "English",
    mood: "Emotional / Healing",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Its Time to Move On.mp3",
  },
  {
    title: "Kurara Easy",
    artist: "M-WIS",
    genre: "Contemporary",
    language: "Mixed",
    mood: "Afro / Relaxed",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Kurara Easy.mp3",
  },
  {
    title: "Living Bread",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "English",
    mood: "Spiritual / Reflective",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Living Bread.mp3",
  },
  {
    title: "My liefde hou vir \u2019n leeftyd",
    artist: "M-WIS",
    genre: "Afrikaans",
    language: "Afrikaans",
    mood: "Romantic",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "My liefde hou vir \u2019n leeftyd.mp3",
  },
  {
    title: "My Wife My Life",
    artist: "M-WIS",
    genre: "R&B",
    language: "English",
    mood: "Romantic / Soul",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "My Wife My Life.mp3",
  },
  {
    title: "Ocean Between Us",
    artist: "M-WIS",
    genre: "Contemporary",
    language: "English",
    mood: "Emotional / Distance",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ocean Between Us.mp3",
  },
  {
    title: "Ons Twee Verdwaal",
    artist: "M-WIS",
    genre: "Afrikaans",
    language: "Afrikaans",
    mood: "Romantic / Emotional",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ons Twee Verdwaal.mp3",
  },
  {
    title: "Re Bina Bosigo",
    artist: "M-WIS",
    genre: "Anthem",
    language: "Mixed",
    mood: "Mood review pending",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Re Bina Bosigo.mp3",
  },
  {
    title: "Strobe Waistline",
    artist: "M-WIS",
    genre: "R&B",
    language: "English",
    mood: "Club / Dance",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Strobe Waistline.mp3",
  },
  {
    title: "Tomorrow Land",
    artist: "M-WIS",
    genre: "Anthem",
    language: "English",
    mood: "Festival / Uplifting",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Tomorrow Land.mp3",
  },
  {
    title: "Voel Weer",
    artist: "M-WIS",
    genre: "Afrikaans",
    language: "Afrikaans",
    mood: "Reflective / Healing",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Voel Weer.mp3",
  },
  {
    title: "You're Still Here",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "English",
    mood: "Emotional / Spiritual",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "You\u2019re Still Here.mp3",
  },
  {
    title: "Always be your child",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "English",
    mood: "Worship / Emotional",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Always be your child.mp3",
  },
  {
    title: "Daar Kom die Alibaba",
    artist: "M-WIS",
    genre: "Afrikaans",
    language: "Afrikaans",
    mood: "Folk / Character",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Daar Kom die Alibama.mp3",
  },
  {
    title: "Draai Soe",
    artist: "M-WIS",
    genre: "Afrikaans",
    language: "Afrikaans",
    mood: "Dance / Local Pop",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Draai Soe.mp3",
  },
  {
    title: "Hier Is Ons",
    artist: "M-WIS",
    genre: "Anthem",
    language: "Afrikaans",
    mood: "Uplifting / Unity",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Hier Is Ons.mp3",
  },
  {
    title: "Kalahari High",
    artist: "M-WIS",
    genre: "Anthem",
    language: "English",
    mood: "Desert / Cinematic",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Kalahari High.mp3",
  },
  {
    title: "Lei Ons Terug Na U, Jesus",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "Afrikaans",
    mood: "Worship",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Lei Ons Terug Na U, Jesus.mp3",
  },
  {
    title: "Mirror Noise",
    artist: "M-WIS",
    genre: "Contemporary",
    language: "English",
    mood: "Alternative / Atmospheric",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Mirror Noise.mp3",
  },
  {
    title: "My Love will last for a Lifetime",
    artist: "M-WIS",
    genre: "R&B",
    language: "English",
    mood: "Romantic Ballad",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "My Love will last for a Lifetime.mp3",
  },
  {
    title: "Ngingasula Okwanamuhla",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "Zulu",
    mood: "African Spiritual",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ngingasula Okwanamuhla.mp3",
  },
  {
    title: "Ons is nooit Alleen nie",
    artist: "M-WIS",
    genre: "Inspirational",
    language: "Afrikaans",
    mood: "Faith / Comfort",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Ons is nooit Alleen nie.mp3",
  },
  {
    title: "Peacock Blue Die Griquas",
    artist: "M-WIS",
    genre: "Anthem",
    language: "Afrikaans",
    mood: "Heritage / Cultural",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Peacock Blue Die Griquas.mp3",
  },
  {
    title: "Re Teng Ga Nyele",
    artist: "M-WIS",
    genre: "Anthem",
    language: "Tswana",
    mood: "African Uplifting",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Re Teng Ga Nyele.mp3",
  },
  {
    title: "Saltwater Eyes",
    artist: "M-WIS",
    genre: "Contemporary",
    language: "English",
    mood: "Coastal / Emotional",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "Saltwater Eyes.mp3",
  },
  {
    title: "The Y",
    artist: "M-WIS",
    genre: "Uncategorized",
    language: "Language pending",
    mood: "Metadata review pending",
    coverImage: catalogueBrowseCoverImage,
    audioFileName: "The Y.mp3",
  },
];

export const catalogueBrowseGenres = Array.from(
  new Set(catalogueBrowseSongs.map((song) => song.genre)),
).sort();

export const catalogueBrowseLanguages = Array.from(
  new Set(catalogueBrowseSongs.map((song) => song.language)),
).sort();
